version: "3.7"

services:
  store-management:
    image: ${DOCKER_CREDS_USR}/storemanagement:${BUILD_ID}-${BRANCH_NAME}
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "${NODE_PORT}:${CONTAINER_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/store?createDatabaseIfNotExist=true
      SERVER_PORT: ${CONTAINER_PORT}


volumes:
  mysql-data-compose:

