management:
    security:
        enabled: false
security:
    basic:
        enabled: false

spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        url: jdbc:mysql://localhost:3306/Store?createDatabaseIfNotExist=true
        username: root
        password: Yessine07+
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        #        database: SQL_SERVER
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: update


lang:
    secondary: ar


server:
    servlet.contextPath: /store-management
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024